const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const dishesJsonPath = path.join(root, 'miniprogram/data/dishes.json');

const existingDishes = JSON.parse(fs.readFileSync(dishesJsonPath, 'utf8'));
console.log(`当前已有菜品数: ${existingDishes.length}`);

const new50Dishes = [
  {
    id: "dish_076",
    name: "俄式红烩牛肉",
    category: "main_meat",
    cookingMethod: "stew",
    taste: ["浓郁", "茄香", "咸鲜", "微酸"],
    spicyLevel: 0,
    ingredients: [
      { name: "牛腩", amount: 350, unit: "g", isMain: true },
      { name: "番茄", amount: 200, unit: "g" },
      { name: "土豆", amount: 150, unit: "g" },
      { name: "洋葱", amount: 80, unit: "g" }
    ],
    mainIngredient: "牛肉",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["西式", "北方", "全国"],
    cookingTimeMinutes: 30,
    difficulty: 2,
    estimatedCostLevel: 3,
    recommendedForTwo: true,
    tags: ["浓郁茄香", "硬菜推荐", "下饭神菜", "俄式风味"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_076.webp",
    dishEmoji: "🥩"
  },
  {
    id: "dish_077",
    name: "番茄蘑菇炖鸡肉",
    category: "main_meat",
    cookingMethod: "stew",
    taste: ["酸甜开胃", "鲜美适口", "嫩滑"],
    spicyLevel: 0,
    ingredients: [
      { name: "鸡腿肉", amount: 350, unit: "g", isMain: true },
      { name: "口蘑", amount: 120, unit: "g" },
      { name: "番茄", amount: 180, unit: "g" },
      { name: "洋葱", amount: 60, unit: "g" }
    ],
    mainIngredient: "鸡肉",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["全国"],
    cookingTimeMinutes: 22,
    difficulty: 2,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["酸甜鲜美", "低脂高蛋白", "家常炖菜", "老少皆宜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_077.webp",
    dishEmoji: "🍗"
  },
  {
    id: "dish_078",
    name: "酸萝卜炖牛肉",
    category: "main_meat",
    cookingMethod: "stew",
    taste: ["酸爽解腻", "生津开胃", "咸鲜入味"],
    spicyLevel: 1,
    ingredients: [
      { name: "牛腩", amount: 350, unit: "g", isMain: true },
      { name: "老坛酸萝卜", amount: 150, unit: "g" },
      { name: "生姜", amount: 15, unit: "g" }
    ],
    mainIngredient: "牛肉",
    bestMonths: [9, 10, 11, 12, 1, 2],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["川渝", "华中", "全国"],
    cookingTimeMinutes: 35,
    difficulty: 2,
    estimatedCostLevel: 3,
    recommendedForTwo: true,
    tags: ["酸爽解腻", "川湘名菜", "秋冬暖胃", "大厨拿手"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_078.webp",
    dishEmoji: "🥩"
  },
  {
    id: "dish_079",
    name: "黑椒香橙慢煨牛腩",
    category: "main_meat",
    cookingMethod: "stew",
    taste: ["果香清雅", "黑椒微辛", "咸鲜醇厚", "解腻"],
    spicyLevel: 1,
    ingredients: [
      { name: "牛腩", amount: 350, unit: "g", isMain: true },
      { name: "鲜香橙片", amount: 80, unit: "g" },
      { name: "洋葱", amount: 60, unit: "g" },
      { name: "黑胡椒粒", amount: 5, unit: "g" }
    ],
    mainIngredient: "牛肉",
    bestMonths: [10, 11, 12, 1, 2],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["全国"],
    cookingTimeMinutes: 35,
    difficulty: 2,
    estimatedCostLevel: 3,
    recommendedForTwo: true,
    tags: ["独家创新", "果香解腻", "西式融合", "硬菜推荐"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_079.webp",
    dishEmoji: "🥩"
  },
  {
    id: "dish_080",
    name: "韩式烤五花肉与鲜切牛上脑",
    category: "main_meat",
    cookingMethod: "stir_fry",
    taste: ["焦香四溢", "鲜嫩多汁", "酱香微辣"],
    spicyLevel: 1,
    ingredients: [
      { name: "原切五花肉", amount: 200, unit: "g", isMain: true },
      { name: "鲜牛上脑", amount: 200, unit: "g", isMain: true },
      { name: "生菜", amount: 150, unit: "g" },
      { name: "大蒜瓣", amount: 30, unit: "g" }
    ],
    mainIngredient: "牛肉",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["韩式", "全国"],
    cookingTimeMinutes: 18,
    difficulty: 2,
    estimatedCostLevel: 3,
    recommendedForTwo: true,
    tags: ["家庭烤肉", "包生菜绝配", "焦香四溢", "双重肉感"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_080.webp",
    dishEmoji: "🥩"
  },
  {
    id: "dish_081",
    name: "蒜香脆皮烤鸡腿",
    category: "main_meat",
    cookingMethod: "braise",
    taste: ["外皮焦脆", "肉汁丰沛", "浓郁蒜香"],
    spicyLevel: 0,
    ingredients: [
      { name: "鲜大鸡全腿", amount: 400, unit: "g", isMain: true },
      { name: "大蒜瓣", amount: 40, unit: "g" },
      { name: "黑胡椒碎", amount: 5, unit: "g" }
    ],
    mainIngredient: "鸡肉",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["全国"],
    cookingTimeMinutes: 28,
    difficulty: 2,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["空气炸锅/烤箱", "外焦里嫩", "蒜香浓郁", "肉食狂喜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_081.webp",
    dishEmoji: "🍗"
  },
  {
    id: "dish_082",
    name: "私房酱香卤牛肉",
    category: "main_meat",
    cookingMethod: "stew",
    taste: ["酱香入骨", "紧实耐嚼", "咸香回甘"],
    spicyLevel: 0,
    ingredients: [
      { name: "牛腱子肉", amount: 450, unit: "g", isMain: true },
      { name: "卤料包(八角桂皮)", amount: 20, unit: "g" },
      { name: "生姜大葱", amount: 30, unit: "g" }
    ],
    mainIngredient: "牛肉",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["北方", "全国"],
    cookingTimeMinutes: 45,
    difficulty: 2,
    estimatedCostLevel: 3,
    recommendedForTwo: true,
    tags: ["私房卤味", "酱香入骨", "硬菜下酒", "二人食常备"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_082.webp",
    dishEmoji: "🥩"
  },
  {
    id: "dish_083",
    name: "鲜甜豌豆炒鸡胸肉",
    category: "secondary_meat",
    cookingMethod: "stir_fry",
    taste: ["清甜脆嫩", "鲜嫩爽口", "咸鲜"],
    spicyLevel: 0,
    ingredients: [
      { name: "嫩甜豌豆", amount: 150, unit: "g" },
      { name: "鸡胸肉", amount: 200, unit: "g", isMain: true },
      { name: "大蒜末", amount: 10, unit: "g" }
    ],
    mainIngredient: "鸡肉",
    bestMonths: [3, 4, 5, 6, 7, 8],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["江南", "全国"],
    cookingTimeMinutes: 12,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["低脂高蛋白", "清甜快手", "减脂两人餐", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_083.webp",
    dishEmoji: "🥓"
  },
  {
    id: "dish_084",
    name: "午餐肉炒青笋",
    category: "secondary_meat",
    cookingMethod: "stir_fry",
    taste: ["咸香油润", "清脆多汁", "微咸微鲜"],
    spicyLevel: 0,
    ingredients: [
      { name: "优质午餐肉", amount: 150, unit: "g", isMain: true },
      { name: "莴笋", amount: 200, unit: "g" },
      { name: "蒜末", amount: 10, unit: "g" }
    ],
    mainIngredient: "猪肉",
    bestMonths: [3, 4, 5, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["全国"],
    cookingTimeMinutes: 10,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["咸香爽脆", "超级下饭", "十分钟搞定", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_084.webp",
    dishEmoji: "🥓"
  },
  {
    id: "dish_085",
    name: "广式腊肠炒西芹",
    category: "secondary_meat",
    cookingMethod: "stir_fry",
    taste: ["腊香咸甜", "芹香脆爽", "镬气"],
    spicyLevel: 0,
    ingredients: [
      { name: "广式腊肠", amount: 120, unit: "g", isMain: true },
      { name: "鲜西芹", amount: 200, unit: "g" },
      { name: "蒜片", amount: 10, unit: "g" }
    ],
    mainIngredient: "猪肉",
    bestMonths: [1, 2, 3, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["粤港", "全国"],
    cookingTimeMinutes: 10,
    difficulty: 1,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["广式风味", "清脆咸甜", "快手家常", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_085.webp",
    dishEmoji: "🥓"
  },
  {
    id: "dish_086",
    name: "萝卜干炒腊肉",
    category: "secondary_meat",
    cookingMethod: "stir_fry",
    taste: ["干香韧脆", "烟熏腊香", "镬气微辣"],
    spicyLevel: 1,
    ingredients: [
      { name: "烟熏腊肉", amount: 150, unit: "g", isMain: true },
      { name: "湖南萝卜干", amount: 100, unit: "g" },
      { name: "青红椒", amount: 50, unit: "g" },
      { name: "大蒜", amount: 15, unit: "g" }
    ],
    mainIngredient: "猪肉",
    bestMonths: [11, 12, 1, 2, 3],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["湘味", "川渝", "全国"],
    cookingTimeMinutes: 14,
    difficulty: 2,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["湘味干香", "下饭神器", "镬气十足", "风味独特"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_086.webp",
    dishEmoji: "🥓"
  },
  {
    id: "dish_087",
    name: "家常番茄香草虾",
    category: "secondary_meat",
    cookingMethod: "stir_fry",
    taste: ["酸甜浓郁", "鲜嫩弹牙", "香草芬芳"],
    spicyLevel: 0,
    ingredients: [
      { name: "鲜活基围虾", amount: 250, unit: "g", isMain: true },
      { name: "番茄", amount: 200, unit: "g" },
      { name: "蒜碎", amount: 15, unit: "g" },
      { name: "香草碎", amount: 5, unit: "g" }
    ],
    mainIngredient: "鲜虾",
    bestMonths: [6, 7, 8, 9, 10],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["全国"],
    cookingTimeMinutes: 12,
    difficulty: 2,
    estimatedCostLevel: 3,
    recommendedForTwo: true,
    tags: ["酸甜开胃", "鲜虾弹牙", "低卡高蛋白", "颜值大菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_087.webp",
    dishEmoji: "🦐"
  },
  {
    id: "dish_088",
    name: "虾籽煨嫩西葫芦",
    category: "secondary_meat",
    cookingMethod: "stir_fry",
    taste: ["清甜多汁", "海味鲜香", "温润滑嫩"],
    spicyLevel: 0,
    ingredients: [
      { name: "鲜西葫芦", amount: 250, unit: "g" },
      { name: "海米虾籽", amount: 40, unit: "g", isMain: true },
      { name: "大蒜", amount: 10, unit: "g" }
    ],
    mainIngredient: "水产",
    bestMonths: [5, 6, 7, 8, 9],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["江南", "全国"],
    cookingTimeMinutes: 9,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["鲜美多汁", "极速快手", "清爽低脂", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_088.webp",
    dishEmoji: "🥓"
  },
  {
    id: "dish_089",
    name: "韩式辣白菜炒五花肉",
    category: "secondary_meat",
    cookingMethod: "stir_fry",
    taste: ["酸辣开胃", "油润焦香", "下饭浓烈"],
    spicyLevel: 2,
    ingredients: [
      { name: "五花肉片", amount: 180, unit: "g", isMain: true },
      { name: "韩式辣白菜", amount: 150, unit: "g" },
      { name: "青椒", amount: 50, unit: "g" },
      { name: "洋葱", amount: 40, unit: "g" }
    ],
    mainIngredient: "猪肉",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["韩式", "北方", "全国"],
    cookingTimeMinutes: 12,
    difficulty: 1,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["酸辣开胃", "油润下饭", "经典韩味", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_089.webp",
    dishEmoji: "🥓"
  },
  {
    id: "dish_090",
    name: "夏日五彩椒炒肉丝",
    category: "secondary_meat",
    cookingMethod: "stir_fry",
    taste: ["爽脆咸鲜", "微甜清爽", "镬气"],
    spicyLevel: 1,
    ingredients: [
      { name: "猪里脊肉", amount: 180, unit: "g", isMain: true },
      { name: "三色甜椒", amount: 150, unit: "g" },
      { name: "蒜末", amount: 10, unit: "g" }
    ],
    mainIngredient: "猪肉",
    bestMonths: [6, 7, 8, 9, 10],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["全国"],
    cookingTimeMinutes: 10,
    difficulty: 1,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["色彩明快", "爽脆咸鲜", "营养均衡", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_090.webp",
    dishEmoji: "🥓"
  },
  {
    id: "dish_091",
    name: "清炒嫩荷兰豆",
    category: "vegetable",
    cookingMethod: "clear_fry",
    taste: ["清甜爽脆", "鲜嫩多汁", "清淡"],
    spicyLevel: 0,
    ingredients: [
      { name: "嫩荷兰豆", amount: 250, unit: "g", isMain: true },
      { name: "大蒜瓣", amount: 15, unit: "g" }
    ],
    mainIngredient: "蔬菜",
    bestMonths: [2, 3, 4, 5, 10, 11],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["华南", "全国"],
    cookingTimeMinutes: 7,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["翠绿爽脆", "清甜低脂", "原汁原味", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_091.webp",
    dishEmoji: "🥬"
  },
  {
    id: "dish_092",
    name: "清炒红苋菜",
    category: "vegetable",
    cookingMethod: "clear_fry",
    taste: ["滑嫩鲜香", "蒜香温润", "清火生津"],
    spicyLevel: 0,
    ingredients: [
      { name: "新鲜红苋菜", amount: 300, unit: "g", isMain: true },
      { name: "大蒜瓣", amount: 20, unit: "g" }
    ],
    mainIngredient: "蔬菜",
    bestMonths: [5, 6, 7, 8, 9],
    availableMonths: [4, 5, 6, 7, 8, 9, 10],
    regions: ["江南", "华南", "全国"],
    cookingTimeMinutes: 6,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["夏令时蔬", "蒜香滑嫩", "清热补铁", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_092.webp",
    dishEmoji: "🥬"
  },
  {
    id: "dish_093",
    name: "广式南乳烧藕片",
    category: "vegetable",
    cookingMethod: "braise",
    taste: ["南乳醇香", "藕片爽脆", "咸甜微鲜"],
    spicyLevel: 0,
    ingredients: [
      { name: "莲藕", amount: 280, unit: "g", isMain: true },
      { name: "红南乳", amount: 25, unit: "g" },
      { name: "蒜末", amount: 10, unit: "g" }
    ],
    mainIngredient: "莲藕",
    bestMonths: [9, 10, 11, 12, 1],
    availableMonths: [8, 9, 10, 11, 12, 1, 2],
    regions: ["粤港", "全国"],
    cookingTimeMinutes: 11,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["粤式特色", "南乳回甘", "爽脆下饭", "时令推荐"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_093.webp",
    dishEmoji: "🥬"
  },
  {
    id: "dish_094",
    name: "清炒奶白菜",
    category: "vegetable",
    cookingMethod: "clear_fry",
    taste: ["鲜嫩多汁", "清甜解腻", "蒜香"],
    spicyLevel: 0,
    ingredients: [
      { name: "矮脚奶白菜", amount: 300, unit: "g", isMain: true },
      { name: "大蒜瓣", amount: 15, unit: "g" }
    ],
    mainIngredient: "蔬菜",
    bestMonths: [10, 11, 12, 1, 2, 3],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["华南", "全国"],
    cookingTimeMinutes: 5,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["极速快手", "鲜嫩甘甜", "绿叶解腻", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_094.webp",
    dishEmoji: "🥬"
  },
  {
    id: "dish_095",
    name: "蒜香清炒佛手瓜",
    category: "vegetable",
    cookingMethod: "clear_fry",
    taste: ["清脆多汁", "微甜清爽", "降火"],
    spicyLevel: 0,
    ingredients: [
      { name: "鲜佛手瓜", amount: 280, unit: "g", isMain: true },
      { name: "大蒜瓣", amount: 15, unit: "g" }
    ],
    mainIngredient: "蔬菜",
    bestMonths: [9, 10, 11, 12],
    availableMonths: [8, 9, 10, 11, 12, 1],
    regions: ["西南", "全国"],
    cookingTimeMinutes: 7,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["秋季时令", "低卡清火", "清甜脆嫩", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_095.webp",
    dishEmoji: "🥬"
  },
  {
    id: "dish_096",
    name: "金枪鱼土豆泥沙拉",
    category: "vegetable",
    cookingMethod: "clear_fry",
    taste: ["咸香绵密", "清爽微酸", "黑椒香"],
    spicyLevel: 0,
    ingredients: [
      { name: "土豆", amount: 250, unit: "g", isMain: true },
      { name: "水浸金枪鱼罐头", amount: 80, unit: "g" },
      { name: "洋葱碎", amount: 30, unit: "g" },
      { name: "黑胡椒粒", amount: 3, unit: "g" }
    ],
    mainIngredient: "土豆",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["全国"],
    cookingTimeMinutes: 12,
    difficulty: 1,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["低脂饱腹", "日式沙拉", "轻食两人食", "免开火"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_096.webp",
    dishEmoji: "🥔"
  },
  {
    id: "dish_097",
    name: "香酥椒盐小土豆",
    category: "vegetable",
    cookingMethod: "stir_fry",
    taste: ["外焦里糯", "椒盐咸香", "葱香扑鼻"],
    spicyLevel: 0,
    ingredients: [
      { name: "带皮小土豆", amount: 300, unit: "g", isMain: true },
      { name: "椒盐粉", amount: 8, unit: "g" },
      { name: "香葱末", amount: 15, unit: "g" }
    ],
    mainIngredient: "土豆",
    bestMonths: [4, 5, 6, 7, 8, 9],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["西南", "全国"],
    cookingTimeMinutes: 16,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["外焦里糯", "街头风味", "越嚼越香", "下酒下饭"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_097.webp",
    dishEmoji: "🥔"
  },
  {
    id: "dish_098",
    name: "下饭干锅土豆片",
    category: "vegetable",
    cookingMethod: "stir_fry",
    taste: ["焦香微辣", "酱香浓郁", "极度下饭"],
    spicyLevel: 1,
    ingredients: [
      { name: "薄切土豆片", amount: 300, unit: "g", isMain: true },
      { name: "洋葱", amount: 60, unit: "g" },
      { name: "大蒜干辣椒", amount: 20, unit: "g" },
      { name: "豆瓣酱", amount: 15, unit: "g" }
    ],
    mainIngredient: "土豆",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["川渝", "华中", "全国"],
    cookingTimeMinutes: 14,
    difficulty: 2,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["焦香微辣", "下饭神菜", "米饭杀手", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_098.webp",
    dishEmoji: "🥔"
  },
  {
    id: "dish_099",
    name: "拉丝芝士焗土豆泥",
    category: "vegetable",
    cookingMethod: "braise",
    taste: ["奶香浓郁", "芝士拉丝", "绵软香甜"],
    spicyLevel: 0,
    ingredients: [
      { name: "土豆", amount: 250, unit: "g", isMain: true },
      { name: "马苏里拉芝士", amount: 80, unit: "g" },
      { name: "甜玉米粒", amount: 40, unit: "g" },
      { name: "纯牛奶", amount: 50, unit: "ml" }
    ],
    mainIngredient: "土豆",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["西式", "全国"],
    cookingTimeMinutes: 18,
    difficulty: 1,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["芝士控", "拉丝绵密", "治愈两人食", "西式暖盘"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_099.webp",
    dishEmoji: "🥔"
  },
  {
    id: "dish_100",
    name: "东北油豆角炖土豆",
    category: "vegetable",
    cookingMethod: "stew",
    taste: ["油润咸香", "软烂绵糯", "酱香入味"],
    spicyLevel: 0,
    ingredients: [
      { name: "东北油豆角", amount: 250, unit: "g", isMain: true },
      { name: "面土豆", amount: 200, unit: "g" },
      { name: "大蒜瓣", amount: 20, unit: "g" }
    ],
    mainIngredient: "豆类",
    bestMonths: [7, 8, 9, 10, 11],
    availableMonths: [6, 7, 8, 9, 10, 11, 12],
    regions: ["东北", "北方", "全国"],
    cookingTimeMinutes: 22,
    difficulty: 2,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["东北风味", "软烂下饭", "家常炖菜", "时令特色"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_100.webp",
    dishEmoji: "🥬"
  },
  {
    id: "dish_101",
    name: "剁椒蒸金针菇",
    category: "vegetable",
    cookingMethod: "steam",
    taste: ["酸辣爽口", "鲜嫩滑脆", "无油烟"],
    spicyLevel: 1,
    ingredients: [
      { name: "鲜金针菇", amount: 250, unit: "g", isMain: true },
      { name: "湖南剁椒", amount: 30, unit: "g" },
      { name: "大蒜蓉", amount: 20, unit: "g" },
      { name: "蒸鱼豉油", amount: 15, unit: "ml" }
    ],
    mainIngredient: "菌菇",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["湘味", "全国"],
    cookingTimeMinutes: 9,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["零油烟蒸菜", "酸辣爽口", "快手解腻", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_101.webp",
    dishEmoji: "🍄"
  },
  {
    id: "dish_102",
    name: "老北京茴香摊鸡蛋",
    category: "egg",
    cookingMethod: "stir_fry",
    taste: ["茴香扑鼻", "金黄松软", "鲜香微甘"],
    spicyLevel: 0,
    ingredients: [
      { name: "土鸡蛋", amount: 3, unit: "个", isMain: true },
      { name: "新鲜茴香", amount: 80, unit: "g" },
      { name: "盐", amount: 3, unit: "g" }
    ],
    mainIngredient: "鸡蛋",
    bestMonths: [3, 4, 5, 6, 10, 11],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["北方", "全国"],
    cookingTimeMinutes: 7,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["老北京经典", "草本芳香", "金黄松软", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_102.webp",
    dishEmoji: "🥚"
  },
  {
    id: "dish_103",
    name: "蒜苗爆炒土鸡蛋",
    category: "egg",
    cookingMethod: "stir_fry",
    taste: ["蒜香浓郁", "滑嫩鲜美", "镬气"],
    spicyLevel: 0,
    ingredients: [
      { name: "土鸡蛋", amount: 3, unit: "个", isMain: true },
      { name: "青蒜苗", amount: 100, unit: "g" },
      { name: "生抽", amount: 10, unit: "ml" }
    ],
    mainIngredient: "鸡蛋",
    bestMonths: [11, 12, 1, 2, 3],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["川渝", "华中", "全国"],
    cookingTimeMinutes: 7,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["蒜香扑鼻", "极速下饭", "金黄滑嫩", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_103.webp",
    dishEmoji: "🍳"
  },
  {
    id: "dish_104",
    name: "凉拌菠菜鸡蛋碎",
    category: "egg",
    cookingMethod: "clear_fry",
    taste: ["清爽解腻", "少油健康", "芝麻醇香"],
    spicyLevel: 0,
    ingredients: [
      { name: "新鲜菠菜", amount: 250, unit: "g" },
      { name: "熟鸡蛋", amount: 2, unit: "个", isMain: true },
      { name: "熟白芝麻", amount: 5, unit: "g" },
      { name: "香油生抽", amount: 10, unit: "ml" }
    ],
    mainIngredient: "鸡蛋",
    bestMonths: [10, 11, 12, 1, 2, 3],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["北方", "全国"],
    cookingTimeMinutes: 8,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["少油轻食", "清爽低卡", "绿叶拌蛋", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_104.webp",
    dishEmoji: "🥚"
  },
  {
    id: "dish_105",
    name: "芝士香烤太阳蛋",
    category: "egg",
    cookingMethod: "braise",
    taste: ["芝香流心", "外微焦内嫩", "黑椒微辛"],
    spicyLevel: 0,
    ingredients: [
      { name: "鸡蛋", amount: 2, unit: "个", isMain: true },
      { name: "马苏里拉芝士", amount: 40, unit: "g" },
      { name: "黑胡椒碎", amount: 2, unit: "g" }
    ],
    mainIngredient: "鸡蛋",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["全国"],
    cookingTimeMinutes: 8,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["免开火", "芝士流心", "快手早餐/晚餐", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_105.webp",
    dishEmoji: "🍳"
  },
  {
    id: "dish_106",
    name: "汪曾祺笔下汪豆腐",
    category: "tofu",
    cookingMethod: "stew",
    taste: ["烫滑鲜美", "火腿咸香", "豆香醇和"],
    spicyLevel: 0,
    ingredients: [
      { name: "老豆腐", amount: 300, unit: "g", isMain: true },
      { name: "金华熟火腿丁", amount: 30, unit: "g" },
      { name: "高汤/鸡汤", amount: 200, unit: "ml" },
      { name: "水淀粉葱末", amount: 15, unit: "g" }
    ],
    mainIngredient: "豆腐",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["江南", "全国"],
    cookingTimeMinutes: 11,
    difficulty: 2,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["文人名菜", "烫滑鲜美", "传统雅致", "两人食暖菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_106.webp",
    dishEmoji: "🥢"
  },
  {
    id: "dish_107",
    name: "外焦里嫩素煎豆腐丸子",
    category: "tofu",
    cookingMethod: "stir_fry",
    taste: ["外焦内嫩", "纯豆香浓郁", "素香怡人"],
    spicyLevel: 0,
    ingredients: [
      { name: "北豆腐", amount: 300, unit: "g", isMain: true },
      { name: "香菇碎", amount: 30, unit: "g" },
      { name: "胡萝卜碎", amount: 30, unit: "g" },
      { name: "小葱碎", amount: 15, unit: "g" }
    ],
    mainIngredient: "豆腐",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["北方", "全国"],
    cookingTimeMinutes: 16,
    difficulty: 2,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["无面粉", "外焦内嫩", "高钙低卡", "家常巧思"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_107.webp",
    dishEmoji: "🥢"
  },
  {
    id: "dish_108",
    name: "干锅酱香千页豆腐",
    category: "tofu",
    cookingMethod: "stir_fry",
    taste: ["Q弹爽滑", "酱香微辣", "焦香下饭"],
    spicyLevel: 1,
    ingredients: [
      { name: "千页豆腐", amount: 250, unit: "g", isMain: true },
      { name: "洋葱片", amount: 50, unit: "g" },
      { name: "青红椒", amount: 40, unit: "g" },
      { name: "蒜末生抽", amount: 15, unit: "g" }
    ],
    mainIngredient: "豆腐",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["川渝", "华中", "全国"],
    cookingTimeMinutes: 11,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["干锅焦香", "Q弹劲道", "下饭神菜", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_108.webp",
    dishEmoji: "🥢"
  },
  {
    id: "dish_109",
    name: "烤鸭架冬瓜清凉消暑汤",
    category: "soup",
    cookingMethod: "boil_soup",
    taste: ["鸭香醇浓", "冬瓜清甜", "胡椒生津"],
    spicyLevel: 0,
    ingredients: [
      { name: "脆烤鸭架骨", amount: 250, unit: "g", isMain: true },
      { name: "冬瓜", amount: 250, unit: "g" },
      { name: "生姜", amount: 15, unit: "g" },
      { name: "白胡椒粉", amount: 2, unit: "g" }
    ],
    mainIngredient: "冬瓜",
    bestMonths: [6, 7, 8, 9, 10],
    availableMonths: [5, 6, 7, 8, 9, 10, 11],
    regions: ["北方", "全国"],
    cookingTimeMinutes: 25,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["夏秋消暑", "鸭香浓郁", "冬瓜吸油", "快手清润"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_109.webp",
    dishEmoji: "🍲"
  },
  {
    id: "dish_110",
    name: "老绍兴雪菜豆腐羹",
    category: "soup",
    cookingMethod: "boil_soup",
    taste: ["咸鲜爽口", "解腻生津", "滑润"],
    spicyLevel: 0,
    ingredients: [
      { name: "嫩豆腐", amount: 250, unit: "g", isMain: true },
      { name: "香雪菜", amount: 60, unit: "g" },
      { name: "鲜笋丁", amount: 40, unit: "g" },
      { name: "水淀粉", amount: 15, unit: "g" }
    ],
    mainIngredient: "豆腐",
    bestMonths: [1, 2, 3, 4, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["江南", "全国"],
    cookingTimeMinutes: 9,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["江南传统", "咸鲜爽口", "极度解腻", "十分钟羹汤"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_110.webp",
    dishEmoji: "🍲"
  },
  {
    id: "dish_111",
    name: "奶油蘑菇鸡肉暖汤",
    category: "soup",
    cookingMethod: "boil_soup",
    taste: ["奶香浓郁", "蘑菇鲜美", "温润醇和"],
    spicyLevel: 0,
    ingredients: [
      { name: "鸡胸肉碎", amount: 150, unit: "g", isMain: true },
      { name: "新鲜口蘑", amount: 120, unit: "g" },
      { name: "洋葱碎", amount: 40, unit: "g" },
      { name: "纯牛奶", amount: 200, unit: "ml" }
    ],
    mainIngredient: "鸡肉",
    bestMonths: [9, 10, 11, 12, 1, 2],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["西式", "全国"],
    cookingTimeMinutes: 16,
    difficulty: 2,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["西式暖汤", "奶香浓郁", "暖胃低卡", "治愈两人食"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_111.webp",
    dishEmoji: "🍲"
  },
  {
    id: "dish_112",
    name: "砂锅香菇腊肠煲仔饭",
    category: "staple_sauce",
    cookingMethod: "stew",
    taste: ["锅巴焦脆", "腊香沁米", "咸甜鲜美"],
    spicyLevel: 0,
    ingredients: [
      { name: "丝苗米", amount: 180, unit: "g", isMain: true },
      { name: "广式腊肠", amount: 100, unit: "g" },
      { name: "鲜香菇", amount: 60, unit: "g" },
      { name: "小油菜", amount: 80, unit: "g" },
      { name: "特调煲仔汁", amount: 20, unit: "ml" }
    ],
    mainIngredient: "猪肉",
    bestMonths: [1, 2, 3, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["粤港", "全国"],
    cookingTimeMinutes: 22,
    difficulty: 2,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["一锅搞定", "焦脆锅巴", "广式经典", "两人食盛宴"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_112.webp",
    dishEmoji: "🍚"
  },
  {
    id: "dish_113",
    name: "菠菜鸡蛋芝士热压三明治",
    category: "staple_sauce",
    cookingMethod: "braise",
    taste: ["外酥里嫩", "芝香浓郁", "营养清爽"],
    spicyLevel: 0,
    ingredients: [
      { name: "全麦吐司", amount: 4, unit: "片", isMain: true },
      { name: "新鲜菠菜", amount: 80, unit: "g" },
      { name: "鸡蛋", amount: 2, unit: "个" },
      { name: "芝士片", amount: 2, unit: "片" }
    ],
    mainIngredient: "鸡蛋",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["全国"],
    cookingTimeMinutes: 8,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["快手三明治", "外脆里爆浆", "元气餐点", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_113.webp",
    dishEmoji: "🥪"
  },
  {
    id: "dish_114",
    name: "干炒牛肉河粉/炒米粉",
    category: "staple_sauce",
    cookingMethod: "stir_fry",
    taste: ["镬气十足", "油润不腻", "牛肉嫩滑"],
    spicyLevel: 0,
    ingredients: [
      { name: "鲜河粉/米粉", amount: 300, unit: "g", isMain: true },
      { name: "牛柳丝", amount: 150, unit: "g" },
      { name: "绿豆芽", amount: 80, unit: "g" },
      { name: "韭黄/小葱", amount: 30, unit: "g" }
    ],
    mainIngredient: "牛肉",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["粤港", "全国"],
    cookingTimeMinutes: 11,
    difficulty: 2,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["大排档顶流", "镬气十足", "弹牙爽滑", "干炒牛河"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_114.webp",
    dishEmoji: "🍜"
  },
  {
    id: "dish_115",
    name: "经典老上海猪油菜饭",
    category: "staple_sauce",
    cookingMethod: "stew",
    taste: ["碧绿爽口", "油香扑鼻", "粒粒分明"],
    spicyLevel: 0,
    ingredients: [
      { name: "大米", amount: 180, unit: "g", isMain: true },
      { name: "上海青菜碎", amount: 150, unit: "g" },
      { name: "熟猪油", amount: 15, unit: "g" },
      { name: "精瘦咸肉丁", amount: 40, unit: "g" }
    ],
    mainIngredient: "蔬菜",
    bestMonths: [10, 11, 12, 1, 2, 3],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["江南", "全国"],
    cookingTimeMinutes: 22,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["老上海经典", "猪油提香", "青翠油润", "一碗治愈"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_115.webp",
    dishEmoji: "🍚"
  },
  {
    id: "dish_116",
    name: "西葫芦火腿凉拌面",
    category: "staple_sauce",
    cookingMethod: "clear_fry",
    taste: ["酸爽开胃", "清凉爽滑", "十分钟搞定"],
    spicyLevel: 1,
    ingredients: [
      { name: "手工拉面/挂面", amount: 180, unit: "g", isMain: true },
      { name: "西葫芦丝", amount: 120, unit: "g" },
      { name: "优质火腿丝", amount: 60, unit: "g" },
      { name: "香醋蒜汁", amount: 20, unit: "ml" }
    ],
    mainIngredient: "猪肉",
    bestMonths: [5, 6, 7, 8, 9],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["北方", "全国"],
    cookingTimeMinutes: 9,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["夏日救命面", "酸爽开胃", "极速快手", "爽口轻负担"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_116.webp",
    dishEmoji: "🍜"
  },
  {
    id: "dish_117",
    name: "常德风味麻辣牛肉米粉",
    category: "staple_sauce",
    cookingMethod: "boil_soup",
    taste: ["湘味地道", "香辣过瘾", "浓郁醇厚"],
    spicyLevel: 2,
    ingredients: [
      { name: "干浆圆米粉", amount: 200, unit: "g", isMain: true },
      { name: "麻辣牛肉浇头", amount: 120, unit: "g" },
      { name: "酸豆角碎", amount: 30, unit: "g" },
      { name: "香葱香菜", amount: 15, unit: "g" }
    ],
    mainIngredient: "牛肉",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["湘味", "全国"],
    cookingTimeMinutes: 13,
    difficulty: 2,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["常德名米粉", "香辣爽滑", "红油牛肉", "嗦粉狂喜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_117.webp",
    dishEmoji: "🍜"
  },
  {
    id: "dish_118",
    name: "经典意式罗勒番茄肉酱意面",
    category: "staple_sauce",
    cookingMethod: "stir_fry",
    taste: ["浓郁挂汁", "茄香微酸", "肉酱扎实"],
    spicyLevel: 0,
    ingredients: [
      { name: "意式直面", amount: 160, unit: "g", isMain: true },
      { name: "牛猪双拼肉酱", amount: 150, unit: "g" },
      { name: "熟番茄泥", amount: 150, unit: "g" },
      { name: "洋葱碎罗勒", amount: 30, unit: "g" }
    ],
    mainIngredient: "牛肉",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["西式", "全国"],
    cookingTimeMinutes: 18,
    difficulty: 2,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["意式经典", "浓郁番茄肉酱", "两人食必做", "经典意面"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_118.webp",
    dishEmoji: "🍜"
  },
  {
    id: "dish_119",
    name: "羊肉白菜冻豆腐粉丝暖锅",
    category: "staple_sauce",
    cookingMethod: "boil_soup",
    taste: ["秋冬暖胃", "清鲜温补", "连汤带面"],
    spicyLevel: 0,
    ingredients: [
      { name: "原切羊肉卷", amount: 200, unit: "g", isMain: true },
      { name: "大白菜", amount: 200, unit: "g" },
      { name: "蜂窝冻豆腐", amount: 150, unit: "g" },
      { name: "龙口粉丝", amount: 60, unit: "g" }
    ],
    mainIngredient: "羊肉",
    bestMonths: [10, 11, 12, 1, 2, 3],
    availableMonths: [10, 11, 12, 1, 2, 3, 4],
    regions: ["北方", "全国"],
    cookingTimeMinutes: 16,
    difficulty: 1,
    estimatedCostLevel: 3,
    recommendedForTwo: true,
    tags: ["冬日暖锅", "清汤羊肉", "连汤带面", "滋补暖身"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_119.webp",
    dishEmoji: "🍲"
  },
  {
    id: "dish_120",
    name: "酸甜茄汁滑蛋虾仁炒饭",
    category: "staple_sauce",
    cookingMethod: "stir_fry",
    taste: ["酸甜适口", "金红诱人", "鲜嫩爽滑"],
    spicyLevel: 0,
    ingredients: [
      { name: "米饭", amount: 250, unit: "g", isMain: true },
      { name: "大虾仁", amount: 120, unit: "g" },
      { name: "鸡蛋", amount: 2, unit: "个" },
      { name: "番茄沙司青豆", amount: 40, unit: "g" }
    ],
    mainIngredient: "鲜虾",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["全国"],
    cookingTimeMinutes: 11,
    difficulty: 1,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["酸甜滑蛋", "色泽金红", "快手炒饭", "老少皆宜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_120.webp",
    dishEmoji: "🍚"
  },
  {
    id: "dish_121",
    name: "老坛酸豆角肉末炒饭",
    category: "staple_sauce",
    cookingMethod: "stir_fry",
    taste: ["酸辣爽脆", "镬气十足", "绝顶开胃"],
    spicyLevel: 1,
    ingredients: [
      { name: "米饭", amount: 250, unit: "g", isMain: true },
      { name: "老坛酸豇豆碎", amount: 80, unit: "g" },
      { name: "精猪肉末", amount: 80, unit: "g" },
      { name: "红朝天椒碎", amount: 10, unit: "g" }
    ],
    mainIngredient: "猪肉",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["湘味", "川渝", "全国"],
    cookingTimeMinutes: 9,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["酸辣开胃", "绝顶下饭", "十分钟快手炒饭", "镬气十足"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_121.webp",
    dishEmoji: "🍚"
  },
  {
    id: "dish_122",
    name: "咸蛋虾米丝瓜汤面线",
    category: "staple_sauce",
    cookingMethod: "boil_soup",
    taste: ["汤浓金黄", "鲜甜滑润", "暖心养胃"],
    spicyLevel: 0,
    ingredients: [
      { name: "手工面线", amount: 150, unit: "g", isMain: true },
      { name: "鲜嫩丝瓜", amount: 150, unit: "g" },
      { name: "咸蛋黄", amount: 2, unit: "个" },
      { name: "金钩海米", amount: 20, unit: "g" }
    ],
    mainIngredient: "丝瓜",
    bestMonths: [6, 7, 8, 9],
    availableMonths: [5, 6, 7, 8, 9, 10],
    regions: ["闽南", "华南", "全国"],
    cookingTimeMinutes: 11,
    difficulty: 1,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["闽南特色", "金汤面线", "清甜滑润", "治愈两人食"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_122.webp",
    dishEmoji: "🍜"
  },
  {
    id: "dish_123",
    name: "家常老北京豆芽鸡蛋炒饼丝",
    category: "staple_sauce",
    cookingMethod: "stir_fry",
    taste: ["咸香焦脆", "豆芽爽脆", "蒜香醋香"],
    spicyLevel: 0,
    ingredients: [
      { name: "手工烙饼丝", amount: 250, unit: "g", isMain: true },
      { name: "绿豆芽", amount: 150, unit: "g" },
      { name: "鸡蛋", amount: 2, unit: "个" },
      { name: "蒜末香醋", amount: 15, unit: "g" }
    ],
    mainIngredient: "鸡蛋",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["北方", "全国"],
    cookingTimeMinutes: 10,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["老北京经典", "焦香爽脆", "家常炒饼", "快手菜"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_123.webp",
    dishEmoji: "🍜"
  },
  {
    id: "dish_124",
    name: "韩式泡菜西葫芦香煎薄饼",
    category: "staple_sauce",
    cookingMethod: "stir_fry",
    taste: ["外酥里软", "酸辣微脆", "焦香扑鼻"],
    spicyLevel: 1,
    ingredients: [
      { name: "韩式泡菜", amount: 100, unit: "g" },
      { name: "西葫芦丝", amount: 120, unit: "g", isMain: true },
      { name: "面粉面糊", amount: 100, unit: "g" },
      { name: "鸡蛋", amount: 1, unit: "个" }
    ],
    mainIngredient: "蔬菜",
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["韩式", "全国"],
    cookingTimeMinutes: 11,
    difficulty: 1,
    estimatedCostLevel: 1,
    recommendedForTwo: true,
    tags: ["韩式煎饼", "外焦内软", "酸辣开胃", "下午茶小点"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_124.webp",
    dishEmoji: "🥪"
  },
  {
    id: "dish_125",
    name: "翡翠菠菜坚果青酱意面",
    category: "staple_sauce",
    cookingMethod: "stir_fry",
    taste: ["清新草本", "坚果浓香", "蒜香橄榄油"],
    spicyLevel: 0,
    ingredients: [
      { name: "意式直面", amount: 160, unit: "g", isMain: true },
      { name: "鲜菠菜青酱", amount: 100, unit: "g" },
      { name: "烘烤坚果碎", amount: 30, unit: "g" },
      { name: "特级初榨橄榄油", amount: 15, unit: "ml" }
    ],
    mainIngredient: "蔬菜",
    bestMonths: [1, 2, 3, 4, 10, 11, 12],
    availableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["西式", "全国"],
    cookingTimeMinutes: 13,
    difficulty: 1,
    estimatedCostLevel: 2,
    recommendedForTwo: true,
    tags: ["低脂健康", "自制菠菜青酱", "清新坚果香", "西式两人餐"],
    enabled: true,
    thumbUrl: "/assets/dishes/dish_125.webp",
    dishEmoji: "🍜"
  }
];

if (new50Dishes.length !== 50) {
  console.error(`错误：新菜品数量为 ${new50Dishes.length}，非 50 道！`);
  process.exit(1);
}

// 保证只保留前 75 道再追加新 50 道（防止重复追加）
const base75 = existingDishes.slice(0, 75);
const all125Dishes = [...base75, ...new50Dishes];

console.log(`全量菜品合并完成，总数: ${all125Dishes.length}`);
fs.writeFileSync(dishesJsonPath, JSON.stringify(all125Dishes, null, 2), 'utf8');
console.log('✅ miniprogram/data/dishes.json 写入成功！');
